import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { UserProvider } from "./context/UserContext";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ReactQueryProvider } from "./ReactQueryProvider";
import { OrganizationProvider } from "./context/OrganizationContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Task Flow",
  description: "Generated by create next app",
  icons: {
    icon: "/TaskFlowIcon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/TaskFlowIcon.png" type="image/png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <OrganizationProvider>
           <Toaster toastOptions={{ style: { color: '#f59e0b', borderRadius: '12px', padding: '16px' } }} />
          {children}
          </OrganizationProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
